name: dispatch

on:
  repository_dispatch:
    types:
      - echo

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: |
          echo ${{ github.event.client_payload.new_tag }}
          echo ${{ github.event.client_payload.type }}